feat: support `no-std` environments
tari-project/bulletproofs-plus pull request #107
Opened 2024-01-09 17:25 UTC by AaronFeickert

This PR makes the library friendly to `no-std` environments.

To do so, it adds two new features:
- `rand` adds the `rand` crate with just enough functionality to support `OsRng`, and enables existing prover and verifier functionality using `OsRng`
- `std` enables corresponding functionality in dependencies

Because both features are enabled by default, this is not a breaking change.

It also updates tests and benchmarks to use a seeded `ChaCha12`-based pseudorandom number generator.

Finally, it adds a `wasm32-unknown-unknown` CI build target to ensure everything works as expected in a `no-std` environment.

2024-01-10 05:06 UTC, SWvheerden approved these changes
utACK

2024-01-11 12:21 UTC, hansieodendaal requested changes
Hi, looking good, just some small changes please.

2024-01-11 12:21 UTC, hansieodendaal commented on src/range_proof.rs
> -    }
I think we can keep this `QuickCheck` test

2024-01-11 12:21 UTC, hansieodendaal commented on .github/workflows/test.yml
>  name: Test
Please add a test for `cargo test --release --no-default-features`

The doc test in `range_proof.rs` can be excluded from this test if appended like this:
```
/// #[cfg(feature = "rand")]
/// use rand::rngs::OsRng;
/// # fn main() {
/// #[cfg(feature = "rand")]
/// {
/// ...
```

2024-01-12 05:51 UTC, hansieodendaal approved these changes
ACK

2024-01-12 05:55 UTC, merged