feat!: clean up serialization
tari-project/bulletproofs-plus pull request #66
Opened 2023-08-23 19:41 UTC by AaronFeickert

Proof serialization and deserialization currently use a custom design that optimizes space. However, the implementation relies heavily on slice indexing and is not particularly clear.

This PR updates the serialization and deserialization logic. It replaces slice indexing with chunked iteration to avoid panic conditions and improve clarity. It also modifies the serialization structure to make bounds checking more intuitive.

Closes #65.

BREAKING CHANGE: Modifies the structure of serialized proofs.

2023-08-24 05:22 UTC, hansieodendaal requested changes
Really nice improvement! All previous unit tests are also passing, so we can add some general fuzzing of selected elements in a next/series of PRs.

We could be a bit more pedantic to improve the maintainability, see suggestions below.

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +    // The number of proof elements fixed in all proofs:
```suggestion
    pub const ELEMENT_SIZE: usize = 32;     (Note: This must go outside 'impl<P> RangeProof<P>')

    // The number of proof elements fixed in all proofs:
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +    const FIXED_PROOF_ELEMENTS: usize = 5;
```suggestion
    const EXTENSION_DEGREE_SIZE: usize = 1;
    // `a, a1, b, r1, s1`
    const FIXED_PROOF_ELEMENTS: usize = 5;
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +            Vec::with_capacity(1 + (self.li.len() + self.ri.len() + Self::FIXED_PROOF_ELEMENTS + self.d1.len()) * 32);
```suggestion
        let mut buf = Vec::with_capacity(
            Self::EXTENSION_DEGREE_SIZE +
                (self.li.len() + self.ri.len() + Self::FIXED_PROOF_ELEMENTS + self.d1.len()) * ELEMENT_SIZE,
        );
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +        if slice.len() < 1 + 32 * ((extension_degree as usize) + Self::FIXED_PROOF_ELEMENTS + 1 + 1) {
```suggestion
        const LI_MIN_LEN: usize = 1;
        const RI_MIN_LEN: usize = 1;
        let di_len = extension_degree as usize;
        if slice.len() <
            Self::EXTENSION_DEGREE_SIZE +
                ELEMENT_SIZE * (di_len + Self::FIXED_PROOF_ELEMENTS + RI_MIN_LEN + LI_MIN_LEN)
        {
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +        if (slice.len() - 1 - 32 * ((extension_degree as usize) + Self::FIXED_PROOF_ELEMENTS)) % (32 * 2) != 0 {
```suggestion
        if (slice.len() - Self::EXTENSION_DEGREE_SIZE - ELEMENT_SIZE * (di_len + Self::FIXED_PROOF_ELEMENTS)) %
            (ELEMENT_SIZE * 2) !=
            0
        {
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +        let mut chunks = slice[1..].chunks_exact(32);
```suggestion
        let mut chunks = slice[Self::EXTENSION_DEGREE_SIZE..].chunks_exact(ELEMENT_SIZE);
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +                let bytes: [u8; 32] = slice
```suggestion
                let bytes: [u8; ELEMENT_SIZE] = slice
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +                let bytes: [u8; 32] = slice
```suggestion
                let bytes: [u8; ELEMENT_SIZE] = slice
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +                let bytes: [u8; 32] = slice
```suggestion
                let bytes: [u8; ELEMENT_SIZE] = slice
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +                let bytes: [u8; 32] = slice
```suggestion
                let bytes: [u8; ELEMENT_SIZE] = slice
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +                let bytes: [u8; 32] = slice
```suggestion
                let bytes: [u8; ELEMENT_SIZE] = slice
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +                let bytes_l: [u8; 32] = l
```suggestion
                let bytes_l: [u8; ELEMENT_SIZE] = l
```

2023-08-24 05:22 UTC, hansieodendaal commented on src/range_proof.rs
> +                let bytes_r: [u8; 32] = r
```suggestion
                let bytes_r: [u8; ELEMENT_SIZE] = r
```

2023-08-24 20:32 UTC, AaronFeickert commented
This is blocked on #68, which fixes a CI toolchain issue.

2023-08-28 07:17 UTC, hansieodendaal approved these changes
ACK

2023-09-11 06:49 UTC, hansieodendaal approved these changes
ACK

2023-09-18 15:49 UTC, hansieodendaal reviewed
ACK

2023-09-18 15:49 UTC, hansieodendaal approved these changes

2023-09-19 17:37 UTC, AaronFeickert commented
See also #79, which adds basic deserialization fuzzing.

2023-09-20 06:53 UTC, SWvheerden approved these changes

2023-09-20 06:53 UTC, merged